In [4]:
import numpy as np

# Difficulty Level Beginner

In [3]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
x=np.arange(10,49)

In [9]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [10]:
np.shape(x)

(39,)

In [11]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [12]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\Numan\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [19]:
y=np.zeros((2,2), dtype=bool)

In [20]:
y

array([[False, False],
       [False, False]])

In [21]:
np.ones((2,2),dtype=bool)

array([[ True,  True],
       [ True,  True]])

# Difficulty Level Easy

In [23]:
x=np.random.randn(5,5)

In [24]:
x

array([[-0.75672894,  0.18793372,  0.69628715, -0.5560435 , -0.69366947],
       [-0.04193492, -0.39769292,  1.09031495,  0.66565485,  0.53866415],
       [-0.27703082,  0.79854112, -0.27027999,  0.35668363,  1.03484243],
       [-0.12259271, -1.70562135, -0.34532579, -0.66388751, -1.11235402],
       [-0.36194721, -0.26996552,  1.50820401, -0.96484448,  0.59338857]])

In [25]:
x=x[::,:-1]

In [27]:
x=np.arange(10,20)

In [28]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
x=x[::-1]

In [30]:
x

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [46]:
x=np.zeros((10))
x[5]=1
x

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
 arr = np.array([1, 2, 3, 4, 5])

In [66]:
arr.dtype

dtype('int32')

In [67]:
z=arr.astype("float32")


In [68]:
z.dtype

dtype('float32')

In [69]:
arr1 = np.array([[1., 2., 3.],
 [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],
 [7., 2., 12.]])

In [70]:
arr1*(arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [5]:
arr1 = np.array([[1., 2., 3.],
 [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],
 [7., 2., 12.]])

In [6]:
comp=arr1==arr2

In [7]:
comp

array([[False, False, False],
       [False, False, False]])

In [9]:
x=np.arange(1,10)

In [10]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
y=x[::2]
y

array([1, 3, 5, 7, 9])

In [48]:
y[::]=-1
y

array([-1, -1, -1, -1, -1])

In [49]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[-6:-2]=12

In [57]:
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

In [67]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [68]:
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [72]:
arr2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Difficulty Level Medium

In [213]:
arr2d[1:2,1:2]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [107]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [108]:
arr3d[0:1,0:1]=64

In [109]:
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [115]:
n=np.arange(1,9).reshape(2,4)

In [116]:
n

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [120]:
n[1:,::]

array([[5, 6, 7, 8]])

In [121]:
m=np.arange(1,9).reshape(2,4)

In [122]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [123]:
m[::,2]

array([3, 7])

In [124]:
w=np.random.randn(10,10)

In [125]:
w

array([[-2.23824146, -1.29121811, -0.10950124, -0.14900019,  0.2418355 ,
        -3.85606419, -1.90915298,  2.25835487,  0.57860476,  0.70460504],
       [ 0.33791064, -1.68001959,  0.40237129, -0.14031174, -0.61599797,
         0.87053198,  0.89334477,  1.17435392, -0.41362938,  0.44528672],
       [ 1.80015338, -2.08161821,  0.83042579, -1.15064226, -0.10537197,
        -0.01419432, -1.42612628, -0.6851666 , -1.02114954, -1.37113506],
       [-1.96738608, -0.86027481,  1.62675519, -0.29590674, -2.30044419,
         0.23104981,  0.6903238 ,  0.33374705, -0.11302112, -0.33274519],
       [ 1.21188638,  0.01198021,  2.25181647, -0.90783392,  0.24176945,
         0.09500585,  0.21080173,  0.24846661, -0.61844445,  1.9998709 ],
       [-0.43121961,  0.4741709 , -0.24630363,  0.0390407 ,  1.98297531,
        -0.12389126, -0.3049479 , -0.90315668, -1.62019261, -0.46831416],
       [-0.99503221, -0.41183944,  1.50333721,  2.07129115, -1.08903533,
         0.75831031,  0.59723482,  0.48821082

In [127]:
np.amax(w)

2.4239374931529665

In [139]:
np.amin(w)

-3.856064187266971

# a = np.array([1,2,3,2,3,4,3,4,5,6]) b =np.array([7,2,10,2,7,4,9,4,9,8])

In [141]:
a=np.array([1,2,3,2,3,4,3,4,5,6]) 
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [212]:
a=np.array([1,2,3,2,3,4,3,4,5,6]) 
b=np.array([7,2,10,2,7,4,9,4,9,8])
print([key for key,val in enumerate(a) if val in set(b)])

[1, 3, 5, 7]


In [142]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [143]:
names.sort()

In [144]:
names

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

In [146]:
arr1=np.random.randn(12)
arr2=np.random.randn(12)

In [148]:
np.maximum(arr1,arr2)

array([-0.12927941, -1.45097579, -0.27128847,  0.93464342, -1.10318287,
        0.28221879,  0.34252977, -1.04375859, -0.39537027,  0.1958031 ,
        0.90999728,  0.88467487])

In [164]:
arr=np.array([1,2,3,4,-1,5])

In [173]:
np.where(arr<=0.5,"0",arr)

array(['1', '2', '3', '4', '0', '5'], dtype='<U11')

In [174]:
n=np.array([1,2,3,4,5])

In [175]:
np.sqrt(n)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [196]:
m=np.random.randint(1,20,size=(5,4))
m

array([[ 8, 10, 10,  7],
       [ 9, 14, 18,  1],
       [19, 17,  9,  4],
       [ 7, 14,  7, 15],
       [10,  8,  2,  9]])

In [197]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.


In [207]:
m=np.random.randn(1,16)

In [208]:
m

array([[-0.26020894,  1.33934409, -1.43322729,  1.45857335,  0.79452061,
         2.38874837,  1.06615863,  3.40047661,  0.86172196, -0.5519751 ,
        -0.11411106, -0.21588716,  0.54301192, -1.15767457, -0.35594414,
        -0.74523541]])

In [209]:
m.reshape((2,2,4))

array([[[-0.26020894,  1.33934409, -1.43322729,  1.45857335],
        [ 0.79452061,  2.38874837,  1.06615863,  3.40047661]],

       [[ 0.86172196, -0.5519751 , -0.11411106, -0.21588716],
        [ 0.54301192, -1.15767457, -0.35594414, -0.74523541]]])

In [216]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [217]:
np.where(names!="Will","not ok",names)

array(['not ok', 'not ok', 'Will', 'not ok', 'Will', 'not ok', 'not ok'],
      dtype='<U6')